/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uniacademia.sca.telas;

import br.edu.uniacademia.sca.arquivo.ArquivoInDiscente;
import br.edu.uniacademia.sca.arquivo.ArquivoOutDiscente;
import br.edu.uniacademia.sca.modelo.Discente;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhon4
 */
public class Aluno extends javax.swing.JFrame {

    private ArquivoInDiscente arqIn = new ArquivoInDiscente();
    private ArquivoOutDiscente arqOut = new ArquivoOutDiscente();
    protected int linhab;

    public Aluno() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            arqIn.abrir();
            arqOut.abrir();
        } catch (IOException ex) {
            Logger.getLogger(Aluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Limpar() {
        txtMatricula.setText("");
        txtBairro.setText("");
        txtCEP.setText("");
        txtCPFALUNO.setText("");
        txtCidade.setText("");
        txtComplemento.setText("");
        txtDataNasc.setText("");
        txtLogradouro.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        txtRGALUNO.setText("");
        jcbEstado.setSelectedIndex(-1);
        bgSexo.clearSelection();
        txtCPFALUNO.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JComboBox<>();
        jckbEstatus = new javax.swing.JCheckBox();
        jlAtivo = new javax.swing.JLabel();
        jbAdicionar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        txtCPFALUNO = new javax.swing.JFormattedTextField();
        txtDataNasc = new javax.swing.JFormattedTextField();
        txtCEP = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtADados = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBAlterar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jbtRemover = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jlCEP = new javax.swing.JLabel();
        jrbSexoM = new javax.swing.JRadioButton();
        jrbSexoF = new javax.swing.JRadioButton();
        jlNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jlCPF = new javax.swing.JLabel();
        jlRG = new javax.swing.JLabel();
        jlDataNasc = new javax.swing.JLabel();
        txtRGALUNO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCA - Aluno");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcbEstado.setSelectedIndex(-1);

        jckbEstatus.setText("Ativo");

        jlAtivo.setText("Estatus:");

        jbAdicionar.setText("Adicionar");
        jbAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAdicionarMouseClicked(evt);
            }
        });
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        try {
            txtCPFALUNO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFALUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFALUNOActionPerformed(evt);
            }
        });

        try {
            txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Logradouro:");

        jLabel4.setText("Número:");

        jtADados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "CPF", "RG", "Nome", "Data Nasc.", "Sexo", "CEP", "Logradouro", "Número", "Complemento", "Bairro", "Cidade", "Estado", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtADados.setColumnSelectionAllowed(true);
        jtADados.getTableHeader().setReorderingAllowed(false);
        jtADados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtADadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtADados);
        jtADados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel5.setText("Cidade:");

        jLabel6.setText("Complemento:");

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jLabel7.setText("Bairro:");

        jbtRemover.setText("Remover");
        jbtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoverActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado:");

        jlCEP.setText("CEP:");

        bgSexo.add(jrbSexoM);
        jrbSexoM.setText("M");
        jrbSexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSexoMActionPerformed(evt);
            }
        });

        bgSexo.add(jrbSexoF);
        jrbSexoF.setText("F");

        jlNome.setText("Nome:");

        jlCPF.setText("CPF:");

        jlRG.setText("RG:");

        jlDataNasc.setText("Data Nasc.:");

        txtRGALUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGALUNOActionPerformed(evt);
            }
        });

        jLabel1.setText("Sexo:");

        jLabel2.setText("Matrícula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlCEP)
                            .addComponent(jlNome)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jlRG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbAdicionar)
                                        .addGap(30, 30, 30)
                                        .addComponent(jbLimpar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jBAlterar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                                .addComponent(jbtRemover))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(8, 8, 8)
                                                        .addComponent(jLabel7))
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(txtNumero)
                                                    .addComponent(txtBairro)))))
                                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRGALUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jlCPF)
                                            .addGap(20, 20, 20)
                                            .addComponent(txtCPFALUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlDataNasc)
                                    .addComponent(jLabel1)
                                    .addComponent(jlAtivo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jckbEstatus)
                                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbSexoM)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbSexoF))))
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDataNasc)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFALUNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCPF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jrbSexoM)
                    .addComponent(jrbSexoF)
                    .addComponent(txtRGALUNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRG))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAtivo)
                    .addComponent(jckbEstatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCEP)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdicionar)
                    .addComponent(jbLimpar)
                    .addComponent(jBAlterar)
                    .addComponent(jbtRemover))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed

        if (txtMatricula.getText().isEmpty() ||txtBairro.getText().isEmpty() || txtCEP.getText().isEmpty() || txtCPFALUNO.getText().isEmpty() || txtCidade.getText().isEmpty()
                || txtDataNasc.getText().isEmpty() || txtLogradouro.getText().isEmpty() || txtNome.getText().isEmpty() || txtRGALUNO.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe os campos marcados", "Informação ausente", JOptionPane.WARNING_MESSAGE);
        } else {
            Discente disc = new Discente();

            disc.setMatricula(txtMatricula.getText());
            disc.setCpf(txtCPFALUNO.getText());
            disc.setRg(txtRGALUNO.getText());
            disc.setBairro(txtBairro.getText());
            disc.setCep(txtCEP.getText());
            disc.setCidade(txtCidade.getText());
            disc.setComplemento(txtComplemento.getText());
            disc.setDataNasc(txtDataNasc.getText());
            disc.setEstado(jcbEstado.getSelectedItem().toString());
            disc.setLogradouro(txtLogradouro.getText());
            disc.setNome(txtNome.getText());
            disc.setNumero(txtNumero.getText());
            if (jrbSexoM.isSelected()) {
                disc.setSexo("Masculino");
            } else if (jrbSexoF.isSelected()) {
                disc.setSexo("Feminino");
            } else {
                JOptionPane.showMessageDialog(null, "Informe o sexo do Aluno(a).", "Informação ausente", JOptionPane.WARNING_MESSAGE);
            }
            if (jckbEstatus.isSelected()) {
                disc.setSituacao("Ativo");
            } else {
                disc.setSituacao("Inativo");
            }

            DefaultTableModel modelo = (DefaultTableModel) jtADados.getModel();

            try {
                arqOut.Adicionar(disc);
            } catch (IOException ex) {
                Logger.getLogger(Aluno.class.getName()).log(Level.SEVERE, null, ex);
            }

            modelo.addRow((Object[]) disc.dadosAlun());

            Limpar();
        }
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed

        this.Limpar();
        txtCPFALUNO.setEnabled(true);
        txtMatricula.setEnabled(true);
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtADadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtADadosMouseClicked

        linhab = jtADados.getSelectedRow();

        txtCPFALUNO.setText(jtADados.getValueAt(linhab, 1).toString());
        txtCPFALUNO.setEnabled(false);
        txtMatricula.setText(jtADados.getValueAt(linhab, 0).toString());
        txtRGALUNO.setText(jtADados.getValueAt(linhab, 2).toString());
        
        txtNome.setText(jtADados.getValueAt(linhab, 3).toString());
        txtDataNasc.setText(jtADados.getValueAt(linhab, 4).toString());
        if (jtADados.getValueAt(linhab, 6).toString().equalsIgnoreCase("Masculino")) {
            jrbSexoM.setSelected(true);
        } else {
            jrbSexoF.setSelected(true);
            
        txtCEP.setText(jtADados.getValueAt(linhab, 6).toString());
        txtLogradouro.setText(jtADados.getValueAt(linhab, 7).toString());
        txtNumero.setText(jtADados.getValueAt(linhab, 8).toString());
        txtComplemento.setText(jtADados.getValueAt(linhab, 9).toString());
        txtBairro.setText(jtADados.getValueAt(linhab, 10).toString());
        txtCidade.setText(jtADados.getValueAt(linhab, 11).toString());

        String estado = jtADados.getValueAt(linhab, 12).toString();

        switch (estado) {
            case "AC":
                jcbEstado.setSelectedIndex(0);
                break;
            case "AL":
                jcbEstado.setSelectedIndex(1);
                break;
            case "AP":
                jcbEstado.setSelectedIndex(2);
                break;
            case "AM":
                jcbEstado.setSelectedIndex(3);
                break;
            case "BA":
                jcbEstado.setSelectedIndex(4);
                break;
            case "CE":
                jcbEstado.setSelectedIndex(5);
                break;
            case "DF":
                jcbEstado.setSelectedIndex(6);
                break;
            case "ES":
                jcbEstado.setSelectedIndex(7);
                break;
            case "GO":
                jcbEstado.setSelectedIndex(8);
                break;
            case "MA":
                jcbEstado.setSelectedIndex(9);
                break;
            case "MT":
                jcbEstado.setSelectedIndex(10);
                break;
            case "MS":
                jcbEstado.setSelectedIndex(11);
                break;
            case "MG":
                jcbEstado.setSelectedIndex(12);
                break;
            case "PA":
                jcbEstado.setSelectedIndex(13);
                break;
            case "PB":
                jcbEstado.setSelectedIndex(14);
                break;
            case "PR":
                jcbEstado.setSelectedIndex(15);
                break;
            case "PE":
                jcbEstado.setSelectedIndex(16);
                break;
            case "PI":
                jcbEstado.setSelectedIndex(17);
                break;
            case "RJ":
                jcbEstado.setSelectedIndex(18);
                break;
            case "RN":
                jcbEstado.setSelectedIndex(19);
                break;
            case "RS":
                jcbEstado.setSelectedIndex(20);
                break;
            case "RO":
                jcbEstado.setSelectedIndex(21);
                break;
            case "RR":
                jcbEstado.setSelectedIndex(22);
                break;
            case "SC":
                jcbEstado.setSelectedIndex(23);
                break;
            case "SP":
                jcbEstado.setSelectedIndex(24);
                break;
            case "SE":
                jcbEstado.setSelectedIndex(25);
                break;
            case "TO":
                jcbEstado.setSelectedIndex(26);
                break;
            default:
                jcbEstado.setSelectedIndex(-1);
               
        }

        if (jtADados.getValueAt(linhab, 13).toString().equalsIgnoreCase("Ativo")) {
            jckbEstatus.setSelected(true);
        }
        
    }//GEN-LAST:event_jtADadosMouseClicked
    }
    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed

        ArrayList<Discente> listat = new ArrayList<Discente>();
        listat = (ArrayList<Discente>) arqIn.getTodos();

        Discente doc = new Discente();

        doc.setMatricula(txtMatricula.getText());
        doc.setCpf(txtCPFALUNO.getText());
        doc.setRg(txtRGALUNO.getText());
        doc.setBairro(txtBairro.getText());
        doc.setCep(txtCEP.getText());
        doc.setCidade(txtCidade.getText());
        doc.setComplemento(txtComplemento.getText());
        doc.setDataNasc(txtDataNasc.getText());
        doc.setEstado(jcbEstado.getSelectedItem().toString());
        doc.setLogradouro(txtLogradouro.getText());
        doc.setNome(txtNome.getText());
        doc.setNumero(txtNumero.getText());
        if (jrbSexoM.isSelected()) {
            doc.setSexo("Masculino");
        } else if (jrbSexoF.isSelected()) {
            doc.setSexo("Feminino");
        } else {
            JOptionPane.showMessageDialog(null, "Informe o sexo do Aluno(a).", "Informação ausente", JOptionPane.WARNING_MESSAGE);
        }
        if (jckbEstatus.isSelected()) {
            doc.setSituacao("Ativo");
        } else {
            doc.setSituacao("Inativo");List<Discente> lista = new ArrayList<Discente>();

        lista = arqIn.getTodos();
        DefaultTableModel modelo = (DefaultTableModel) jtADados.getModel();

        for (int i = jtADados.getRowCount() - 1; i >= 0; --i) {
            modelo.removeRow(i);
        }

        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow((Object[]) lista.get(i).dadosAlun());
        }
        }
        
        listat.get(linhab).setMatricula(doc.getMatricula());
        listat.get(linhab).setCpf(doc.getCpf());
        listat.get(linhab).setRg(doc.getRg());
        listat.get(linhab).setNome(doc.getNome());
        listat.get(linhab).setBairro(doc.getBairro());
        listat.get(linhab).setCep(doc.getCep());
        listat.get(linhab).setCidade(doc.getCidade());
        listat.get(linhab).setComplemento(doc.getComplemento());
        listat.get(linhab).setDataNasc(doc.getDataNasc());
        listat.get(linhab).setEstado(doc.getEstado());
        listat.get(linhab).setLogradouro(doc.getLogradouro());
        listat.get(linhab).setNumero(doc.getNumero());
        listat.get(linhab).setSexo(doc.getSexo());
        listat.get(linhab).setSituacao(doc.getSituacao());

        try {
            arqOut.recadastrar_todos(listat);
        } catch (IOException ex) {
            Logger.getLogger(Aluno.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Valor alterado com sucesso!");

        Limpar();
        txtCPFALUNO.setEnabled(true);

        DefaultTableModel modelo = (DefaultTableModel) jtADados.getModel();

        if (jtADados.getRowCount() > 0) {
            for (int i = jtADados.getRowCount() - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

        List<Discente> listat2 = new ArrayList<Discente>();
        listat2 = arqIn.getTodos();

        for (int i = 0; i < listat2.size(); i++) {
            modelo.addRow((Object[]) listat2.get(i).dadosAlun());

        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jbtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoverActionPerformed

        DefaultTableModel modelo = (DefaultTableModel) jtADados.getModel();
        List<Discente> list = new ArrayList<Discente>();
        ArrayList<Discente> nova_list = new ArrayList<Discente>();
        linhab = jtADados.getSelectedRow();
        Object nome = modelo.getValueAt(linhab, 0);
        list = arqIn.getTodos();

        for (int i = 0; i < list.size(); i++) {
            if (!(list.get(i).getCpf().equals(txtCPFALUNO.getText()))) {
                nova_list.add(list.get(i));
            }
        }
        try {
            arqOut.recadastrar_todos(nova_list);
        } catch (IOException ex) {
            Logger.getLogger(Aluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        Limpar();
        modelo.removeRow(linhab);
        txtCPFALUNO.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Registro apagado com sucesso");

    }//GEN-LAST:event_jbtRemoverActionPerformed

    private void jrbSexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSexoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSexoMActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    List<Discente> lista = new ArrayList<Discente>();

        lista = arqIn.getTodos();
        DefaultTableModel modelo = (DefaultTableModel) jtADados.getModel();

        for (int i = jtADados.getRowCount() - 1; i >= 0; --i) {
            modelo.removeRow(i);
        }

        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow((Object[]) lista.get(i).dadosAlun());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jbAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAdicionarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAdicionarMouseClicked

    private void txtRGALUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGALUNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGALUNOActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void txtCPFALUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFALUNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFALUNOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbtRemover;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JCheckBox jckbEstatus;
    private javax.swing.JLabel jlAtivo;
    private javax.swing.JLabel jlCEP;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlDataNasc;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlRG;
    private javax.swing.JRadioButton jrbSexoF;
    private javax.swing.JRadioButton jrbSexoM;
    private javax.swing.JTable jtADados;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPFALUNO;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JTextField txtRGALUNO;
    // End of variables declaration//GEN-END:variables

}
